okta:
  oauth2:
    issuer: https://dev-5977069.okta.com/oauth2/default
    clientId: 0oa3x761lF4fVuTxB5d6
    clientSecret: SnmDdtsjihceeL5Y68S1LRg1qo3j9P_ad93zfMwz

spring:
  data:
    r2dbc:
      repositories:
        enabled: true

  r2dbc:
    url: r2dbc:h2:mem://./testdb